name: Build (CI)

permissions:
  contents: read

on:
  push:
    branches: [dev]
    paths-ignore: &ignored
      - '**/.editorconfig'
      - '**/.gitignore'
      - '**/.gitattributes'
      - '**/*.md'
      - '**/LICENSE'
      - '**/LICENCE'
      - 'PCL.Core.Test/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
  pull_request:
    paths-ignore: *ignored
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - configuration: CI
            architecture: x64
            language: CSharp
            project_file: "Plain Craft Launcher 2/Plain Craft Launcher 2.csproj"
          - configuration: CI
            architecture: ARM64
            language: CSharp
            project_file: "Plain Craft Launcher 2/Plain Craft Launcher 2.csproj"
          - configuration: CI
            architecture: x64
            language: VisualBasic
            project_file: "Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj"
          - configuration: CI
            architecture: ARM64
            language: VisualBasic
            project_file: "Plain Craft Launcher 2/Plain Craft Launcher 2.vbproj"
      fail-fast: false

    uses: ./.github/workflows/reusable-build.yml
    with:
      configuration: ${{ matrix.configuration }}
      architecture: ${{ matrix.architecture }}
      language: ${{ matrix.language }}
      project_file: ${{ matrix.project_file }}
    secrets: inherit
